POST http://localhost:8080/api/chat/
Content-Type: application/json

{
    "message": "Give me summary of why it's good to go outside"
}

###
POST http://localhost:8080/api/chat/
Content-Type: application/json

{
    "message": "Why is it bad to eat junk foods a lot?"
}

###
POST https://docker-ai-fastapi-python-4m94j.ondigitalocean.app/api/chat/
Content-Type: application/json

{
    "message": "Good Morning 1!"
}

###
POST https://docker-ai-fastapi-python-4m94j.ondigitalocean.app/api/chat/
Content-Type: application/json

{
    "message": "Good Morning 2!"
}

###
POST https://docker-ai-fastapi-python-4m94j.ondigitalocean.app/api/chat/
Content-Type: application/json

{
    "message": "Good Morning 3!"
}

###
GET https://docker-ai-fastapi-python-4m94j.ondigitalocean.app/api/chat/recent/
###

curl http://localhost:12434/engines/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "ai/gemma3",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Please write 500 words about the fall of Rome."
            }
        ]
    }'
