services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 
    environment:
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
        - action: restart
          path: ./backend/src/
    depends_on:
      - db_service
  
  db_service:
    image: postgres:17.5
    ports:
      - 5432:5432
    volumes:
      - dc_managed_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_database

volumes:
  dc_managed_db_volume: