services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # uncomment this to reload the server when the code changes with "sync"
    environment:
      - PORT=8000
      - MY_PROJECT=hello world
    env_file:
      - .env
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
        # - action: sync
        #   path: ./backend/src/
        #   target: /app
        - action: restart
          path: ./backend/src/
          
  static_html:
    build:
      context: ./static_html
      dockerfile: static.Dockerfile
    ports:
      - 8000:8000
      - 3000:8000
    command: python -m http.server 8000 
    volumes:
      - ./static_html/src:/app
